### ISSUE TITLE
Partially not working 1.16

### ISSUE THREAD

**Issue by Processhf** [Enaium-FabricMC/NoExpensive#1]
Not working as intended on Fabric 1.16.

Will not work on client or server. Mod is confirmed to be running in server console. 

Ability to add mending to infinity and multishot to piercing is working, but only on single player. On servers, it shows the item in anvil but when clicking to add the mending book, item disappears. Items are also still appearing as "too expensive".

**Comment by Enaium** [comment]
I did not expect a solution

**Comment by Processhf** [comment]
I'm not sure I understand

**Comment by Oneoeigh** [comment]
I tried a sword with all enchants in single player mode. Mending it in anvil still shows too expensive.

**Comment by Enaium** [comment]
> 
> 
> I tried a sword with all enchants in single player mode. Mending it in anvil still shows too expensive.

Fixing soon

**Comment by Enaium** [comment]
already fixed
