### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by mezotv** [Enaium-FabricMC/NoExpensive#10]
I tried to put mending on my sharpness 4 knockback 2 unbreaking 1 sword but it still says to expensive. 

![image](https://user-images.githubusercontent.com/68947960/156366881-9f052e17-f8f6-4c73-96a9-a7bff24b7292.png)

**Comment by Enaium** [comment]
game version？

**Comment by mezotv** [comment]
1.18.2

**Comment by Enaium** [comment]
![Snipaste_2022-03-03_20-03-54](https://user-images.githubusercontent.com/32991121/156561292-6f0f2291-a6d6-4624-958f-b2bc0b24c3ec.jpg)
