### ISSUE TITLE
Compatible versions set wrong in CurseForge

### ISSUE THREAD

**Issue by RandomGgames** [Enaium-FabricMC/NoExpensive#11]
In Curseforge, mod file says it's only compatible with 1.19-Snapshots, but 1.19 isn't listed as a compatible version as well (which it should if it is compatible with 1.19.
This is causing mod managers to think the mod is out of date/incompatible with the 1.19 game version and only work with snapshots and thus not work with it. Please fix!

**Comment by Enaium** [comment]
ok
