### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by wemdne** [Enaium-FabricMC/NoExpensive#12]
IDK if there is a limit of a number of enchantments or sth, but there is a problem when I try to make an enchantment book with all the enchantments that are not incompatible, where the required level doesn't show up, the enchanted book shows up in the third spot in the anvil menu but it's not clickable. I also couldn't enchant anything with that book after I found this problem. The game version is 1.19
<img width="1470" alt="截屏2022-08-22 下午7 30 21" src="https://user-images.githubusercontent.com/87947139/186037380-645aa747-0006-4fe9-b791-1f3e72c18bc8.png">
<img width="1470" alt="截屏2022-08-22 下午7 29 52" src="https://user-images.githubusercontent.com/87947139/186037382-2e183edb-faa9-4f8a-8883-e8c4051ee3b3.png">

**Comment by wemdne** [comment]
I added a mod that adds more enchantments btw. Idk if the problem comes from there

**Comment by wemdne** [comment]
I tried with other combinations of enchantments, and the same problem was found. The enchantment descriptions went out of the screen due to the number of enchantments, so I couldn't find a number. But I think there is a limit to the number of enchantments when enchanting. Since vanilla minecraft doesn't have that many enchantments, the problem seems not very affecting to those who play minecraft without any mods that add enchantments. It could affect ppl with mods that add more enchantments tho, which this mod becomes more helpful to.

**Comment by wemdne** [comment]
The mod I added is combat enchantments on curseforge, here's the link if you wanna test it out https://www.curseforge.com/minecraft/mc-mods/combat-enchantments

**Comment by Enaium** [comment]
> I tried with other combinations of enchantments, and the same problem was found. The enchantment descriptions went out of the screen due to the number of enchantments, so I couldn't find a number. But I think there is a limit to the number of enchantments when enchanting. Since vanilla minecraft doesn't have that many enchantments, the problem seems not very affecting to those who play minecraft without any mods that add enchantments. It could affect ppl with mods that add more enchantments tho, which this mod becomes more helpful to.

附魔数量在原版中并没有限制

**Comment by wemdne** [comment]
是不是因为原版没有那么多的附魔以达到这个限制呢

**Comment by Enaium** [comment]
> 是不是因为原版没有那么多的附魔以达到这个限制呢

去掉兼容限制后原版都能把所有附魔叠到一块

**Comment by Enaium** [comment]
启动游戏的时候日志有没有什么错误

**Comment by wemdne** [comment]
游戏可以正常启动

**Comment by Enaium** [comment]
试试不加这个mod会显示什么

**Comment by wemdne** [comment]
原版的确可以重叠所有附魔 我数一下有多少

**Comment by wemdne** [comment]
不过加mod之后没附魔几个就出问题了

**Comment by Enaium** [comment]
> 不过加mod之后没附魔几个就出问题了

什么意思

**Comment by wemdne** [comment]
原版的附魔数量达不到触发问题，原版附魔不多，但是加了mod之后就不能把原版和mod的附魔叠到一本书上了

**Comment by wemdne** [comment]
抱歉没表达清楚，加了mod之后可以附魔，但是有数量限制

**Comment by wemdne** [comment]
就是假设原版有15个附魔，mod也有15个，我把原版的附魔叠到了一本书上，我也可以继续叠mod的附魔，但是叠不满了，可能叠到25个就触发问题了

**Comment by wemdne** [comment]
因为那个mod的附魔可以被你的mod影响从而解除限制，但是叠到一定数量又叠不下去，所以我才觉得有可能是有个限制

**Comment by Enaium** [comment]
那么就是这个附魔的mod有数量限制？

**Comment by wemdne** [comment]
我数了下

**Comment by wemdne** [comment]
只能有33个附魔

**Comment by Enaium** [comment]
那么在附魔数量不限制的情况下加入我这个mod可以用不

**Comment by wemdne** [comment]
原版的也覆盖不全，除去附魔冲突（不包括你mod移除的冲突），总共有34个附魔

**Comment by wemdne** [comment]
附魔数量限制可能是因为这个mod，但是去掉这个mod就导致我只能附魔到39级

**Comment by wemdne** [comment]
我附魔了除去时运，消失诅咒，绑定诅咒，冰霜行者，精准采集，激流和引雷以外的所有附魔，共34个，我看一下只有这个mod的话问题还在不在

**Comment by wemdne** [comment]
问题依然存在

**Comment by wemdne** [comment]
看来原版附魔比我想象中的要多lol

**Comment by wemdne** [comment]
重新数了下，是35个，把一开始的漏了，不过还有7个附魔是附魔不了的这点没变

**Comment by Enaium** [comment]
好吧，找了一下，原版对nbt list有大小限制，为37个
