### ISSUE TITLE
1.20 Fabric server: Anvil shows incorrect combine/repair cost, Mixin error in the log

### ISSUE THREAD

**Issue by pajicadvance** [Enaium-FabricMC/NoExpensive#16]
[latest.log](https://github.com/Enaium-FabricMC/NoExpensive/files/11750510/latest.log)
`@Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin from mod noexpensive`

On the client connected to the server, the anvil always shows that the cost of any operation is the maximum cost set in the config, otherwise works as expected.

Edit: The mod is installed both client and server side.

**Comment by Enaium** [comment]
Ignore the warn

**Comment by BBloom81** [comment]
To pile on, 1.20 and 1.20.1 Fabric.
Mod on client and server.

No matter what the max level is set to, 0, 10000, and anywhere in between, the cost always shows as 39.

**Comment by Enaium** [comment]
Fixed
