### ISSUE TITLE
Unninstalling the mod in 1.20 results in bug that does not let you enchant anything

### ISSUE THREAD

**Issue by Shzeg** [Enaium-FabricMC/NoExpensive#18]
So I'm in this server with the mod installed, and we decided to remove it because we didn't like it anymore. The thing is, that once it was removed (with all of it's customs compatibilities), it removed ALL enchantments compatibilities from the game, meaning we couldn't enchant even vanilla combinations, like  mending+unbreaking. I'd like to know if there's a way to solve this (apart from adding said vanilla compatibilities with the mod). Maybe some folder with the mods config that can be erased, idk.

**Comment by Enaium** [comment]
Fixed

**Comment by Shzeg** [comment]
How and where did u fixed it? I want the vanilla compatibilities back in my server, how can I do it?

**Comment by Enaium** [comment]
> How and where did u fixed it? I want the vanilla compatibilities back in my server, how can I do it?

To use the latest version of the mod
