### ISSUE TITLE
The mod causes the game to crash on versions 1.16.5 and 1.19.2.

### ISSUE THREAD

**Issue by Fleepe** [Enaium-FabricMC/NoExpensive#20]
Minecraft 1.16.5 can't start at all, so it doesn't have crashlog, only latest.log :
[latest.log](https://github.com/Enaium-FabricMC/NoExpensive/files/11849552/latest.log)

Minecraft 1.19.2 can run, but I can't enter any world - it immediately crashes.
[crash-2023-06-23_17.37.40-client.txt](https://github.com/Enaium-FabricMC/NoExpensive/files/11849523/crash-2023-06-23_17.37.40-client.txt)
[latest.log](https://github.com/Enaium-FabricMC/NoExpensive/files/11849528/latest.log)

Everything is updated: Windows 10 (22H2), Adoptium Java 8 (8.0.372.7) for 1.16.5 and 17 (17.0.7.7) for 1.19.2 and of course all mods are updated too.

**Comment by Enaium** [comment]
Try 1. 19. 4

**Comment by Fleepe** [comment]
> Try 1.19. 4,only fabric-api and noexpensive

Works fine

**Comment by Fleepe** [comment]
> > > Try 1.19. 4,only fabric-api and noexpensive
> > 
> > 
> > Works fine
> 
> Ok

So you won't fix it? I forgot to test version 1.16.5 and after checking now it still crashes
