### ISSUE TITLE
The game still crashes on 1.19.2 version

### ISSUE THREAD

**Issue by Fleepe** [Enaium-FabricMC/NoExpensive#21]
Even after updating the mod to version 1.7.0, the game still crashes:

[crash-2023-06-24_11.44.37-client.txt](https://github.com/Enaium-FabricMC/NoExpensive/files/11856000/crash-2023-06-24_11.44.37-client.txt)
[latest.log](https://github.com/Enaium-FabricMC/NoExpensive/files/11856001/latest.log)

It will be unfortunate if you stop supporting updates to version 1.19.2, because it has many more mods than 1.19.4

**Comment by Enaium** [comment]
> Even after updating the mod to version 1.7.0, the game still crashes:
> 
> [crash-2023-06-24_11.44.37-client.txt](https://github.com/Enaium-FabricMC/NoExpensive/files/11856000/crash-2023-06-24_11.44.37-client.txt) [latest.log](https://github.com/Enaium-FabricMC/NoExpensive/files/11856001/latest.log)
> 
> It will be unfortunate if you stop supporting updates to version 1.19.2, because it has many more mods than 1.19.4

Outdated versions are no longer supported, so you may want to use the version that was once supported.
