### ISSUE TITLE
Server connection drops when using `compatibility list` command with an empty list in 1.20.1

### ISSUE THREAD

**Issue by manuelgrabowski** [Enaium-FabricMC/NoExpensive#23]
Not super critical, but when removing all compatibility entries (I only want to remove the max anvil repair cost) and then trying to confirm that with `/noexpensive compatibility list`, your server connection drops with `%s`. Server seems to be chugging along fine, so not really a big issue. Doesn't happen in Single Player.

**Comment by Enaium** [comment]
Fixed
