### ISSUE TITLE
[BUG?] Should "Too expensive" message not be replaced by the enchantement level cost ?

### ISSUE THREAD

**Issue by Skulrag** [Enaium-FabricMC/NoExpensive#25]
Context / Issue :
When am trying to repair / combine something in the anvil that goes among the anvil vanilla limit, it shows "Too expensive" message.

It still shows the right message when hovering the item.

Is it considered as an issue ? It's my first time using the mod, am trying this in solo to put it on my server after.

![2023-07-19_10 22 08](https://github.com/Enaium-FabricMC/NoExpensive/assets/58217414/45d6abf5-599b-4125-b3b5-d0b0631bcad1)
![2023-07-19_10 22 42](https://github.com/Enaium-FabricMC/NoExpensive/assets/58217414/050bf817-1179-4a19-9d78-1d4eaa2dc015)

**Comment by Enaium** [comment]
No, because it doesn't change the screen on the server.
