### ISSUE TITLE
[Dupe] Duping Golden Apples

### ISSUE THREAD

**Issue by Zunwolf1896** [Enaium-FabricMC/NoExpensive#28]
Couple of my players have informed us 

"I found a bug where If you put enchanted golden apples in a grindstone then you get a golden apple and the enchanted apple back"

This extra golden apple can be eaten and does give all the effects. I am awaiting a clip from one of the players that I will post in here so you can see. 

MC: 1.20.1
Fabric API:  0.90.7
NoExpensive: 1.9.0

**Comment by Zunwolf1896** [comment]
https://github.com/Enaium-FabricMC/NoExpensive/assets/88537204/7ae8dcf6-05f4-4822-bed8-a3f8aaad261b

A player gave me a clip of the bug.

**Comment by Enaium** [comment]
https://github.com/Enaium-FabricMC/NoExpensive/assets/32991121/6817cdb8-84ae-4125-ae6a-668d5c023b1a
