### ISSUE TITLE
Possible (massive) improvement over the mixin

### ISSUE THREAD

**Issue by LeoCTH** [Enaium-FabricMC/NoExpensive#4]
An `@Overwrite` is *really, **really*** not needed in this case. After analyzing the code, I've found one and *only* one difference between yours and vanilla's:

Vanilla:
```java
if (this.levelCost.get() >= 40 && !this.player.getAbilities().creativeMode) {
    itemStack2 = ItemStack.EMPTY;
}
```

NoExpensive:
```java
if (this.levelCost.get() >= 40 && !this.player.getAbilities().creativeMode) {
    this.levelCost.set(39);
}
```

If this is the only change there is no reason to overwrite the entire method, as you can easily skip this condition by multiple ways: by redirecting `levelCost.get` to always return a value lower than 40, or modifying the constant to `Integer.MAX_VALUE`, or by redirecting `player.getAbilities().creativeMode` to always return true. If any of them are used the code inside the if statement won't even run, achieving the same goal.
~~Also in my opinion locking the cost *again* when the code above the check literally does the same thing is an odd thing to do. Just leave the code block blank. :tiny_potato:~~

**Comment by Enaium** [comment]
thanks
