### ISSUE TITLE
ISSUE with too expensive

### ISSUE THREAD

**Issue by Gouthamkrishna2006** [Enaium-FabricMC/NoExpensive#9]
The wordings too expensive is no longer seen when placing my bow which is a good thing, but after I placed my mending book the end product comes in the third square for a split moment and goes and I am no longer able to take the bow with the mending applied. Please look into the issue.

**Comment by Enaium** [comment]
game version？

**Comment by Gouthamkrishna2006** [comment]
1.18.1

**Comment by Gouthamkrishna2006** [comment]
i also tried in 1.18, but still the same result

**Comment by Gouthamkrishna2006** [comment]
hmm, we just have to add the said mod to the mods folder right, me noob thats why asking

**Comment by Enaium** [comment]
[![7FIyE8.jpg](https://s4.ax1x.com/2022/01/09/7FIyE8.jpg)](https://imgtu.com/i/7FIyE8)

[![7FIWgs.jpg](https://s4.ax1x.com/2022/01/09/7FIWgs.jpg)](https://imgtu.com/i/7FIWgs)

No issue found

**Comment by Gouthamkrishna2006** [comment]
my friend the problem is when the thing is too expensive to use the anvil..
![1](https://user-images.githubusercontent.com/76784208/148675032-2f52ed3c-4a6f-431c-a2c1-53b71447f42e.PNG)
![2](https://user-images.githubusercontent.com/76784208/148675038-71dd9e1d-203e-4abf-9540-8c646896f5f3.PNG)
when adding the mending book the end product comes for a split second and goes...after reading through the comments in curse forge it appears I'm not the only one having this issue

**Comment by Gouthamkrishna2006** [comment]
oh sorry but may I know will it work in servers because, in singleplayer I didn't check, I just checked in the server that we started

**Comment by Enaium** [comment]
> 

server also needs to add this mod

**Comment by Gouthamkrishna2006** [comment]
hmm, would u be kind to share a video in which it shows how we could do the same
